#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

INSTALL_USER="${SUDO_USER:-${USER}}"
INSTALL_GROUP="$(id -gn "${INSTALL_USER}")"
INSTALL_DIR="${REPO_ROOT}"
SERVICE_NAME="medical-diorama.service"
SERVICE_TEMPLATE="${REPO_ROOT}/deploy/systemd/medical-diorama.service"
SERVICE_DEST="/etc/systemd/system/${SERVICE_NAME}"
ENV_FILE="${INSTALL_DIR}/.env"
WAYFIRE_CONFIG="/home/${INSTALL_USER}/.config/wayfire.ini"
ADMIN_USERNAME="admin"
ADMIN_PASSWORD=""
SECRET_KEY=""
SKIP_APT=0
SKIP_WAYFIRE=0
REQUIRED_GROUPS=(gpio spi video input render i2c)

usage() {
    cat <<'EOF'
Usage: sudo ./deploy/install_pi.sh [options]

Installs Medical Diorama on a Raspberry Pi from the current repo checkout.

Options:
  --user USERNAME           Linux user that will run the service
  --install-dir PATH        Repo install path used in the systemd unit
  --admin-username NAME     Web admin username for a new .env file
  --admin-password PASS     Web admin password for a new .env file
  --secret-key KEY          Flask secret key for a new .env file
  --skip-apt                Skip apt package installation
  --skip-wayfire            Skip Wayfire rotation changes
  --help                    Show this help text
EOF
}

log() {
    printf '[install] %s\n' "$*"
}

require_root() {
    if [[ "${EUID}" -ne 0 ]]; then
        echo "Run this installer with sudo." >&2
        exit 1
    fi
}

generate_secret_key() {
    python3 - <<'PY'
import secrets
print(secrets.token_hex(32))
PY
}

ensure_env_file() {
    if [[ -f "${ENV_FILE}" ]]; then
        log ".env already exists at ${ENV_FILE}; leaving it unchanged"
        return
    fi

    if [[ -z "${ADMIN_PASSWORD}" ]]; then
        ADMIN_PASSWORD="changeme"
    fi
    if [[ -z "${SECRET_KEY}" ]]; then
        SECRET_KEY="$(generate_secret_key)"
    fi

    log "Creating ${ENV_FILE}"
    cat > "${ENV_FILE}" <<EOF
# Generated by deploy/install_pi.sh
SECRET_KEY=${SECRET_KEY}
ADMIN_USERNAME=${ADMIN_USERNAME}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
EOF
    chown "${INSTALL_USER}:${INSTALL_GROUP}" "${ENV_FILE}"
    chmod 600 "${ENV_FILE}"
}

install_apt_packages() {
    if [[ "${SKIP_APT}" -eq 1 ]]; then
        log "Skipping apt package installation"
        return
    fi

    log "Installing apt packages"
    apt-get update
    apt-get install -y \
        git \
        python3 \
        python3-venv \
        python3-pip \
        python3-dev \
        libjpeg-dev \
        zlib1g-dev \
        libopenjp2-7 \
        libtiff6 \
        libfreetype6 \
        libatlas-base-dev \
        libsdl2-2.0-0 \
        libsdl2-image-2.0-0 \
        libsdl2-mixer-2.0-0 \
        libsdl2-ttf-2.0-0 \
        libsdl2-dev \
        libportmidi0 \
        libportmidi-dev \
        libgpiod-dev \
        libgpiod2 \
        xrandr \
        wlr-randr
}

ensure_group_memberships() {
    local group_name
    for group_name in "${REQUIRED_GROUPS[@]}"; do
        if getent group "${group_name}" > /dev/null; then
            log "Ensuring ${INSTALL_USER} is in group ${group_name}"
            usermod -aG "${group_name}" "${INSTALL_USER}"
        else
            log "Group ${group_name} does not exist on this system; skipping"
        fi
    done
}

install_python_deps() {
    log "Creating virtualenv in ${INSTALL_DIR}/.venv"
    sudo -u "${INSTALL_USER}" python3 -m venv "${INSTALL_DIR}/.venv"

    log "Installing Python dependencies"
    sudo -u "${INSTALL_USER}" "${INSTALL_DIR}/.venv/bin/python" -m pip install --upgrade pip
    sudo -u "${INSTALL_USER}" "${INSTALL_DIR}/.venv/bin/python" -m pip install -r "${INSTALL_DIR}/requirements.txt"
}

install_service() {
    local install_uid
    install_uid="$(id -u "${INSTALL_USER}")"

    log "Installing systemd unit to ${SERVICE_DEST}"
    sed \
        -e "s|^User=.*|User=${INSTALL_USER}|" \
        -e "s|^Group=.*|Group=${INSTALL_GROUP}|" \
        -e "s|/home/bhv/Medical-Diorama|${INSTALL_DIR}|g" \
        -e "s|/run/user/1000|/run/user/${install_uid}|g" \
        "${SERVICE_TEMPLATE}" > "${SERVICE_DEST}"

    systemctl daemon-reload
    systemctl enable --now "${SERVICE_NAME}"
}

ensure_wayfire_rotation() {
    if [[ "${SKIP_WAYFIRE}" -eq 1 ]]; then
        log "Skipping Wayfire configuration"
        return
    fi

    local config_dir
    config_dir="$(dirname "${WAYFIRE_CONFIG}")"
    mkdir -p "${config_dir}"

    if [[ ! -f "${WAYFIRE_CONFIG}" ]]; then
        touch "${WAYFIRE_CONFIG}"
        chown "${INSTALL_USER}:${INSTALL_GROUP}" "${WAYFIRE_CONFIG}"
    fi

    if ! grep -q '^\[output:HDMI-A-1\]$' "${WAYFIRE_CONFIG}" 2>/dev/null; then
        log "Appending Wayfire rotation entries to ${WAYFIRE_CONFIG}"
        cat >> "${WAYFIRE_CONFIG}" <<'EOF'

[output:HDMI-A-1]
transform = 90

[output:HDMI-A-2]
transform = 90
EOF
        chown "${INSTALL_USER}:${INSTALL_GROUP}" "${WAYFIRE_CONFIG}"
    else
        log "Wayfire output section already present in ${WAYFIRE_CONFIG}; leaving it unchanged"
    fi
}

parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --user)
                INSTALL_USER="$2"
                INSTALL_GROUP="$(id -gn "${INSTALL_USER}")"
                WAYFIRE_CONFIG="/home/${INSTALL_USER}/.config/wayfire.ini"
                shift 2
                ;;
            --install-dir)
                INSTALL_DIR="$2"
                ENV_FILE="${INSTALL_DIR}/.env"
                shift 2
                ;;
            --admin-username)
                ADMIN_USERNAME="$2"
                shift 2
                ;;
            --admin-password)
                ADMIN_PASSWORD="$2"
                shift 2
                ;;
            --secret-key)
                SECRET_KEY="$2"
                shift 2
                ;;
            --skip-apt)
                SKIP_APT=1
                shift
                ;;
            --skip-wayfire)
                SKIP_WAYFIRE=1
                shift
                ;;
            --help)
                usage
                exit 0
                ;;
            *)
                echo "Unknown argument: $1" >&2
                usage
                exit 1
                ;;
        esac
    done
}

main() {
    require_root
    parse_args "$@"

    log "Installing for user ${INSTALL_USER}"
    log "Install directory ${INSTALL_DIR}"

    install_apt_packages
    ensure_group_memberships
    install_python_deps
    ensure_env_file
    ensure_wayfire_rotation
    install_service

    log "Installation complete"
    log "Web UI: http://<pi-ip>:5000"
    log "Service status: sudo systemctl status ${SERVICE_NAME}"
    log "Reboot or log out/in before first use so new group memberships take effect"
}

main "$@"
